CREATE table CPU(
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar not null ,
    price int not null check ( price>0 ),
    description varchar
);
CREATE table RAM(
                    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                    name varchar not null ,
                    price int not null check ( price>0 ),
                    description varchar
);
CREATE table Board(
                    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                    name varchar not null ,
                    price int not null check ( price>0 ),
                    description varchar
);
CREATE table Power_Supply(
                      id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                      name varchar not null ,
                      price int not null check ( price>0 ),
                      description varchar
);
CREATE table Cooling_System(
                            id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                            name varchar not null ,
                            price int not null check ( price>0 ),
                            description varchar
);
CREATE table Cases(
                            id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                            name varchar not null ,
                            price int not null check ( price>0 ),
                            description varchar
);
CREATE table Main_Memory(
                            id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                            name varchar not null ,
                            price int not null check ( price>0 ),
                            description varchar
);
CREATE table Graphic_Card(
                            id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                            name varchar not null ,
                            price int not null check ( price>0 ),
                            description varchar
);
create table Buyer(
    id int primary key generated by default as identity,
    name varchar not null,
    surname varchar,
    phone_number varchar(20),
    email varchar unique
);
create table Master(
    id int primary key generated by default as identity,
    name varchar not null,
    surname varchar,
    phone_number varchar(20),
    email varchar unique
);
create table Computer(
                         id int primary key generated by default as identity,
                         name varchar,
                         cpu_id int references CPU(id) on delete set null,
                         ram_id int references RAM(id) on delete set null,
                         board_id int references Board(id) on delete set null,
                         power_supply_id int references Power_Supply(id) on delete set null,
                         cooling_system_id int references Cooling_System(id) on delete set null,
                         case_id int references Cases(id) on delete set null,
                         main_memory_id int references Main_Memory(id) on delete set null,
                         graphic_card_id int references Graphic_Card(id) on delete set null,
                         price_computer int,
                         description varchar
);
create table "Order"(
                        order_id int primary key generated by default as identity,
                        date date,
                        computer_id int references Computer(id) on delete set null,
                        master_id int references Master(id) on delete set null,
                        buyer_id int references Buyers(id) on delete set null,
                        price int
);

